language: Swift
osx_image: xcode9.1
xcode_project: ReactiveDataDisplayManager.xcodeproj
xcode_scheme: ReactiveDataDisplayManager
before_install:
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild test -scheme ReactiveDataDisplayManager -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' | xcpretty -c 
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -t 3cc9e099-0607-47af-aa4e-d0dd33709e35
