language: Swift
osx_image: xcode9.4
xcode_project: ReactiveDataDisplayManager.xcodeproj
xcode_scheme: ReactiveDataDisplayManager
before_install:
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild test -scheme ReactiveDataDisplayManager -configuration Debug -showBuildSettings -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -enableCodeCoverage YES -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.4' | xcpretty -c 
  
after_success:
  - bash <(curl -s https://codecov.io/bash) -J 'ReactiveDataDisplayManager'
