language: Swift
osx_image: xcode9.1
xcode_project: Notty.xcodeproj # path to your xcodeproj folder
xcode_scheme: Notty
before_install:
  - gem install cocoapods
  - gem install xcpretty -N
  - brew update
  - brew install swiftlint || true
script:
  - set -o pipefail
  - xcodebuild test -workspace Notty.xcworkspace -scheme Notty -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO -destination 'platform=iOS Simulator,name=iPhone 8,OS=11.1' | xcpretty -c 
  - swiftlint
